---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ptable_dict: {}
    os_ptable_map:
      - name: Debian9
        ptables:
          - Kickstart default
          - preseed default
      - name: Centos6
        ptables:
          - Kickstart default
          - entire SCSI disk
      - name: SLES12
        ptables:
          - preseed default
          - entire SCSI disk
  tasks:
    - set_fact:
        ptable_dict: "{{ ptable_dict
                         | combine( {item.1: ptable_dict[item.1]
                                    | default([])
                                    | union([item.0.name] )  }) }}"
      with_subelements:
        - "{{ os_ptable_map }}"
        - ptables
    - debug:
        var: ptable_dict
...
