---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    customer_order_list: {}
    product_order_list:
      - name: product1
        customers:
          - customer_a
          - customer_b
      - name: product2
        customers:
          - customer_b
          - customer_c
  tasks:
    - set_fact:
        customer_order_list: "{{ customer_order_list
                         | combine( {item.1:
                                      customer_order_list[item.1]
                                    | default([])
                                    | union([item.0.name] )  }) }}"
      with_subelements:
        - "{{ product_order_list }}"
        - customers
    - debug:
        var: customer_order_list
...
