---
- hosts: localhost
  connection: local
  gather_facts: False
  vars: []
  tasks:
    - name: deploy cronjob
      cron:
        name: "run latest playbook"
        minute: "*/2"
        job: >
          ansible-pull
            -U https://github.com/manuelbonk/ansible-pull.git
            -i 'localhost,' play.yaml"
...
