---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    default_server:
      kernel_memory: 64m
      pull: True
      state: started
    microservices:
      - image: httpd
        name: apache http server
        kernel_memory: 512m
      - image: nginx
        name: nginx loadbalancer
        cpu_count: 4
  tasks:
    - debug: var=item
      loop: "{{ microservices }}"
    - set_fact:
        result:  "{{ result | default([]) + [default_server | combine( item , recursive=True)] }}"
      loop: "{{ microservices }}"
    - debug: var=result
...
