---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    default_server:
      kernel_memory: 64m
      cpu_count: 2
      state: started

    a_new_server:
      name: "a new server"
      kernel_memory: 32m
  tasks:
    - set_fact:
        server: "{{ default_server | combine(a_new_server)}}"
#        server: "{{ default_server | combine(a_new_server, recursive=True)}}"
    - debug: var=server
...
